apiVersion: v1
kind: Secret
metadata:
  name: grafana-observability-env
  namespace: monitoring
type: Opaque
stringData:
  # Datasource UIDs
  DS_PROMETHEUS: "prometheus"
  DS_LOKI: "loki"
  DS_TEMPO: "tempo"

  # Org
  GRAFANA_ORG_ID: "1"

  # Backend URLs
  PROMETHEUS_URL: "http://prometheus.monitoring.svc.cluster.local:9090"
  LOKI_URL: "http://loki.monitoring.svc.cluster.local:3100"
  TEMPO_URL: "http://tempo.monitoring.svc.cluster.local:3200"
